# 块浏览器默认配置模板
LibraryPath=我的常用块
NasLibraryPath=我的常用块
LocalMirrorPath=我的常用块
PreferLocalWhenNasUnavailable=1
AllowNasSync=0
CurrentLibraryMode=Local
UserName=
ThumbSize=128
InsertScale=1
InsertRotation=0
FormWidth=1000
FormHeight=650
